/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ArticleList: typeof import("./components/ArticleList.vue")["default"];
    ArticleListTest: typeof import("./components/ArticleListTest.vue")["default"];
    ArticleManage: typeof import("./components/ArticleManage.vue")["default"];
    CommentManage: typeof import("./components/CommentManage.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCheckTag: typeof import("element-plus/es")["ElCheckTag"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ForgetPwd: typeof import("./components/ForgetPwd.vue")["default"];
    LoginCon: typeof import("./components/LoginCon.vue")["default"];
    RegisterCon: typeof import("./components/RegisterCon.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    UserCenter: typeof import("./components/UserCenter.vue")["default"];
    UserHome: typeof import("./components/UserHome.vue")["default"];
    UserManage: typeof import("./components/UserManage.vue")["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
  }
}
